import type {Metadata} from "next";
import "./globals.css"
import Menu from "@/components/menu/Menu";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <Menu/>
        <hr/>
        {children}
        </body>
        </html>
    );
}
